project_name: siftool

release:
  github:
    owner: hpcng
    name: sif
  prerelease: auto

builds:
  - binary: siftool
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm
      - arm64
    goarm:
      - 6
      - 7
    env:
      - CGO_ENABLED=0
    ldflags: '-s -w -X main.version={{ .Version }} -X main.commit={{ .FullCommit }} -X main.date={{ .CommitDate }} -X main.builtBy=goreleaser'
    main: ./cmd/siftool
    mod_timestamp: '{{ .CommitTimestamp }}'

archives:
  - format: tar.gz
    wrap_in_directory: true
    name_template: '{{ .ProjectName }}-{{ .Version }}-{{ .Os }}-{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    files:
      - README.md

checksum:
  name_template: '{{ .ProjectName }}-{{ .Version }}-checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
      - '^dev:'
      - '^docs:'
      - '^test:'
      - '^Merge branch'
      - '^Merge pull request'
